### ISSUE TITLE
HTTPError raised by client

### ISSUE THREAD

**Issue by jKuenel** [KWARC/faulumpus#2]
When I start the server by `python3 server.py -visualize` and then the client by `python3 client.py -step`, I get the following traceback, while I just replaced a row of letters and digits by `CHARS` since I wasn't sure if this could leak something:

~~~
Traceback (most recent call last):
  File "client.py", line 95, in <module>
    firstSquare = connection.newGame()
  File "client.py", line 59, in newGame
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Malformed request: illegal key for url: http://127.0.0.1:8000/CHARS
~~~

Server is up and accessible. Same problem on Kubuntu and Windows.

**Comment by jKuenel** [comment]
Found it myself: The password has to be more than 10 characters long. So what remains is just to make this requirement more clear: `agent.py` only says it *should* be more than 10 characters long, and the raised Exception is not very helpful in identifying the problem.

**Comment by jfschaefer** [comment]
I agree that this is a problem that should be fixed. However, I'm hesitant to change the server while the challenge is still ongoing.
For now, I've just changed *should* to *must* in `agent.py` (on the devel branch).
